In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
engine = create_engine("sqlite:///../data/sales_data.db")

print("Database Connected Successfully!")

Database Connected Successfully!

In [3]:
query = """
SELECT *
FROM superstore_cleaned;
"""

df = pd.read_sql(query, engine)

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960
1,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620
2,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368
3,6,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860
4,7,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280

In [4]:
query = """
SELECT *
FROM superstore_cleaned
WHERE Category = 'Furniture';
"""

df = pd.read_sql(query, engine)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960
1,6,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860
2,24,US-2018-156909,2018-07-16,2018-07-18,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372
3,30,US-2016-150630,2016-09-17,2016-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,FUR-FU-10004848,Furniture,Furnishings,"Howard Miller 13-3/4"" Diameter Brushed Chrome ...",124.200
4,37,CA-2017-117590,2017-12-08,2017-12-10,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080.0,Central,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",190.920

In [5]:
query = """
SELECT *
FROM superstore_cleaned
ORDER BY Sales DESC;
"""

df = pd.read_sql(query, engine)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,9733,CA-2015-114321,2015-08-20,2015-08-25,Standard Class,NC-18535,Nick Crebassa,Corporate,United States,Hampton,Virginia,23666.0,South,FUR-CH-10001797,Furniture,Chairs,"Safco Chair Connectors, 6/Carton",500.240
1,3732,CA-2016-109575,2016-09-18,2016-09-23,Standard Class,KH-16630,Ken Heidel,Corporate,United States,Clinton,Maryland,20735.0,East,TEC-PH-10000730,Technology,Phones,Samsung Galaxy S4 Active,499.990
2,2264,CA-2017-131065,2017-11-14,2017-11-16,Second Class,AA-10375,Allen Armold,Consumer,United States,Atlanta,Georgia,30318.0,South,TEC-AC-10004145,Technology,Accessories,Logitech diNovo Edge Keyboard,499.980
3,5620,US-2017-124163,2017-09-25,2017-09-30,Standard Class,SC-20695,Steve Chapman,Corporate,United States,La Crosse,Wisconsin,54601.0,Central,TEC-AC-10001908,Technology,Accessories,Logitech Wireless Headset h800,499.950
4,2969,CA-2018-167941,2018-11-06,2018-11-09,Second Class,JF-15565,Jill Fjeld,Consumer,United States,Fayetteville,North Carolina,28314.0,South,OFF-AP-10002118,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",499.584

In [8]:
query = """
SELECT *
FROM superstore_cleaned
ORDER BY Sales DESC
LIMIT 10;
"""

df = pd.read_sql(query, engine)
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,9733,CA-2015-114321,2015-08-20,2015-08-25,Standard Class,NC-18535,Nick Crebassa,Corporate,United States,Hampton,Virginia,23666.0,South,FUR-CH-10001797,Furniture,Chairs,"Safco Chair Connectors, 6/Carton",500.240
1,3732,CA-2016-109575,2016-09-18,2016-09-23,Standard Class,KH-16630,Ken Heidel,Corporate,United States,Clinton,Maryland,20735.0,East,TEC-PH-10000730,Technology,Phones,Samsung Galaxy S4 Active,499.990
2,2264,CA-2017-131065,2017-11-14,2017-11-16,Second Class,AA-10375,Allen Armold,Consumer,United States,Atlanta,Georgia,30318.0,South,TEC-AC-10004145,Technology,Accessories,Logitech diNovo Edge Keyboard,499.980
3,5620,US-2017-124163,2017-09-25,2017-09-30,Standard Class,SC-20695,Steve Chapman,Corporate,United States,La Crosse,Wisconsin,54601.0,Central,TEC-AC-10001908,Technology,Accessories,Logitech Wireless Headset h800,499.950
4,2969,CA-2018-167941,2018-11-06,2018-11-09,Second Class,JF-15565,Jill Fjeld,Consumer,United States,Fayetteville,North Carolina,28314.0,South,OFF-AP-10002118,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",499.584
5,8595,CA-2018-159667,2018-11-09,2018-11-13,Standard Class,PM-19135,Peter McVee,Home Office,United States,Jacksonville,Florida,32216.0,South,TEC-PH-10004094,Technology,Phones,Motorola L703CM,499.168
6,5220,CA-2018-145653,2018-09-01,2018-09-01,Same Day,CA-12775,Cynthia Arntzen,Consumer,United States,Detroit,Michigan,48205.0,Central,FUR-CH-10004875,Furniture,Chairs,Harbour Creations 67200 Series Stacking Chairs,498.260
7,8339,CA-2015-153087,2015-12-27,2016-01-03,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Decatur,Alabama,35601.0,South,TEC-AC-10003198,Technology,Accessories,Enermax Acrylux Wireless Keyboard,498.000
8,7558,CA-2018-159506,2018-11-27,2018-12-02,Standard Class,JR-16210,Justin Ritter,Corporate,United States,Columbus,Indiana,47201.0,Central,OFF-BI-10004519,Office Supplies,Binders,GBC DocuBind P100 Manual Binding Machine,497.940
9,1775,CA-2015-118976,2015-04-28,2015-05-03,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Baltimore,Maryland,21215.0,East,OFF-ST-10000877,Office Supplies,Storage,Recycled Steel Personal File for Standard File...,497.610

In [7]:
query = """
SELECT
    Category,
    SUM(Sales) AS Total_Sales
FROM superstore_cleaned
GROUP BY Category;
"""

df = pd.read_sql(query, engine)
df

          Category  Total_Sales
0        Furniture  243370.4348
1  Office Supplies  337978.7500
2       Technology  225412.1850

In [9]:
query = """
SELECT
    Category,
    SUM(Sales) AS Total_Sales
FROM superstore_cleaned
GROUP BY Category
HAVING SUM(Sales) > 100000;
"""

df = pd.read_sql(query, engine)
df

          Category  Total_Sales
0        Furniture  243370.4348
1  Office Supplies  337978.7500
2       Technology  225412.1850

In [10]:
import sqlite3

print(sqlite3.sqlite_version)

3.37.2

In [11]:
query = """
CREATE VIEW IF NOT EXISTS category_sales AS
SELECT
    Category,
    SUM(Sales) AS Total_Sales
FROM superstore_cleaned
GROUP BY Category;
"""

with engine.begin() as conn:
    conn.exec_driver_sql(query)

print("View created successfully!")

View created successfully!

In [12]:
query = """
SELECT * FROM category_sales;
"""

df = pd.read_sql(query, engine)
df

          Category  Total_Sales
0        Furniture  243370.4348
1  Office Supplies  337978.7500
2       Technology  225412.1850

In [13]:
query = """
WITH category_summary AS
(
    SELECT
        Category,
        SUM(Sales) AS Total_Sales
    FROM superstore_cleaned
    GROUP BY Category
)

SELECT *
FROM category_summary;
"""

df = pd.read_sql(query, engine)
df

          Category  Total_Sales
0        Furniture  243370.4348
1  Office Supplies  337978.7500
2       Technology  225412.1850

In [14]:
query = """
SELECT
    "Customer Name",
    Sales,
    ROW_NUMBER() OVER (ORDER BY Sales DESC) AS Row_Num
FROM superstore_cleaned
LIMIT 10;
"""

df = pd.read_sql(query, engine)
df

     Customer Name    Sales  Row_Num
0    Nick Crebassa  500.240        1
1       Ken Heidel  499.990        2
2     Allen Armold  499.980        3
3    Steve Chapman  499.950        4
4       Jill Fjeld  499.584        5
5      Peter McVee  499.168        6
6  Cynthia Arntzen  498.260        7
7     Tamara Chand  498.000        8
8    Justin Ritter  497.940        9
9  Muhammed Yedwab  497.610       10

In [15]:
query = """
SELECT
    "Customer Name",
    Sales,
    RANK() OVER (ORDER BY Sales DESC) AS Sales_Rank
FROM superstore_cleaned
LIMIT 10;
"""

df = pd.read_sql(query, engine)
df

     Customer Name    Sales  Sales_Rank
0    Nick Crebassa  500.240           1
1       Ken Heidel  499.990           2
2     Allen Armold  499.980           3
3    Steve Chapman  499.950           4
4       Jill Fjeld  499.584           5
5      Peter McVee  499.168           6
6  Cynthia Arntzen  498.260           7
7     Tamara Chand  498.000           8
8    Justin Ritter  497.940           9
9  Muhammed Yedwab  497.610          10

In [16]:
query = """
SELECT
    "Order Date",
    Sales,
    LAG(Sales) OVER (ORDER BY "Order Date") AS Previous_Sales
FROM superstore_cleaned
LIMIT 10;
"""

df = pd.read_sql(query, engine)
df

   Order Date    Sales  Previous_Sales
0  2015-01-03   16.448             NaN
1  2015-01-04   11.784          16.448
2  2015-01-04  272.736          11.784
3  2015-01-04    3.540         272.736
4  2015-01-05   19.536           3.540
5  2015-01-06   19.440          19.536
6  2015-01-06   12.780          19.440
7  2015-01-06    5.480          12.780
8  2015-01-06  391.980           5.480
9  2015-01-06   31.120         391.980

In [17]:
query = """
SELECT
    "Order Date",
    Sales,
    LEAD(Sales) OVER (ORDER BY "Order Date") AS Next_Sales
FROM superstore_cleaned
LIMIT 10;
"""

df = pd.read_sql(query, engine)
df

   Order Date    Sales  Next_Sales
0  2015-01-03   16.448      11.784
1  2015-01-04   11.784     272.736
2  2015-01-04  272.736       3.540
3  2015-01-04    3.540      19.536
4  2015-01-05   19.536      19.440
5  2015-01-06   19.440      12.780
6  2015-01-06   12.780       5.480
7  2015-01-06    5.480     391.980
8  2015-01-06  391.980      31.120
9  2015-01-06   31.120       6.540

In [18]:
query = """
SELECT
    "Product Name",
    SUM(Sales) AS Total_Sales
FROM superstore_cleaned
GROUP BY "Product Name"
ORDER BY Total_Sales DESC
LIMIT 5;
"""

pd.read_sql(query, engine)

                                       Product Name  Total_Sales
0                        KI Adjustable-Height Table     3950.781
1   Global Wood Trimmed Manager's Task Chair, Khaki     3621.004
2        Situations Contoured Folding Chairs, 4/Set     2959.866
3         Global High-Back Leather Tilter, Burgundy     2841.069
4  Nortel Meridian M3904 Professional Digital phone     2802.618

In [19]:
query = """
SELECT
    Category,
    SUM(Sales) AS Total_Sales
FROM superstore_cleaned
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, engine)

          Category  Total_Sales
0  Office Supplies  337978.7500
1        Furniture  243370.4348
2       Technology  225412.1850

In [20]:
query = """
SELECT
    Region,
    SUM(Sales) AS Total_Sales
FROM superstore_cleaned
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, engine)

    Region  Total_Sales
0     West  269677.1345
1     East  229351.9580
2  Central  180207.3958
3    South  127524.8815

In [21]:
query = """
SELECT
    State,
    SUM(Sales) AS Total_Sales
FROM superstore_cleaned
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

          State  Total_Sales
0    California  169805.9015
1      New York   90610.8130
2         Texas   70585.8508
3  Pennsylvania   45393.3630
4    Washington   41204.6160
5          Ohio   36112.0100
6      Illinois   35891.4590
7       Florida   27572.4255
8      Michigan   25603.5360
9       Arizona   20935.8050

In [22]:
query = """
SELECT
    Segment,
    SUM(Sales) AS Total_Sales
FROM superstore_cleaned
GROUP BY Segment
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, engine)

       Segment  Total_Sales
0     Consumer  431161.0998
1    Corporate  236416.9998
2  Home Office  139183.2702

In [23]:
query = """
SELECT
    "Customer Name",
    SUM(Sales) AS Total_Sales
FROM superstore_cleaned
GROUP BY "Customer Name"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

     Customer Name  Total_Sales
0       Paul Prost     4196.928
1  Laura Armstrong     3751.798
2     Ken Lonsdale     3371.691
3         John Lee     3114.772
4    William Brown     3101.582
5      Rick Wilson     2879.891
6     Noel Staavos     2857.753
7    Arthur Gainer     2806.851
8      Clay Ludtke     2801.042
9       Joel Eaton     2783.489

In [24]:
query = """
SELECT
    substr("Order Date",1,7) AS Month,
    SUM(Sales) AS Total_Sales
FROM superstore_cleaned
GROUP BY Month
ORDER BY Month;
"""

pd.read_sql(query, engine)

      Month  Total_Sales
0   2015-01    5406.9670
1   2015-02    3263.6720
2   2015-03   11967.3240
3   2015-04   11032.7010
4   2015-05   10452.7310
5   2015-06   10238.1566
6   2015-07   10859.4270
7   2015-08   12662.9305
8   2015-09   20542.6848
9   2015-10   13696.0970
10  2015-11   22213.4837
11  2015-12   23391.4655
12  2016-01    5486.9160
13  2016-02    5063.5290
14  2016-03    9952.0440
15  2016-04   13127.2505
16  2016-05   10635.2580
17  2016-06   10161.2990
18  2016-07   12858.6910
19  2016-08   12472.8222
20  2016-09   20190.5780
21  2016-10   15004.3020
22  2016-11   27443.5283
23  2016-12   27095.6280
24  2017-01    8508.9570
25  2017-02    9152.2500
26  2017-03   15139.9460
27  2017-04   12706.4200
28  2017-05   16039.6300
29  2017-06   17741.5220
30  2017-07   15321.1920
31  2017-08   13239.3678
32  2017-09   27815.8195
33  2017-10   15272.4930
34  2017-11   30778.7640
35  2017-12   30129.3720
36  2018-01   11874.9630
37  2018-02   10090.2834
38  2018-03   21955.5408
39  2018-04   15659.2966
40  2018-05   19952.2074
41  2018-06   20890.9412
42  2018-07   20286.1710
43  2018-08   17341.1820
44  2018-09   37356.3220
45  2018-10   21534.4682
46  2018-11   37281.0380
47  2018-12   35473.7368

In [25]:
query = """
SELECT
    "Ship Mode",
    COUNT(*) AS Total_Orders
FROM superstore_cleaned
GROUP BY "Ship Mode";
"""

pd.read_sql(query, engine)

        Ship Mode  Total_Orders
0     First Class          1325
1        Same Day           473
2    Second Class          1671
3  Standard Class          5186

In [26]:
query = """
SELECT
    "Sub-Category",
    SUM(Sales) AS Total_Sales
FROM superstore_cleaned
GROUP BY "Sub-Category"
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, engine)

   Sub-Category  Total_Sales
0        Phones  116360.0900
1       Storage   93655.4840
2   Accessories   91726.9400
3        Chairs   91544.5390
4         Paper   74207.0540
5   Furnishings   67580.5060
6       Binders   59452.1830
7    Appliances   46720.7290
8        Tables   44075.8235
9     Bookcases   40169.5663
10          Art   25592.3860
11    Envelopes   15523.3900
12     Machines   12465.3170
13       Labels   10932.0620
14     Supplies    8893.5020
15      Copiers    4859.8380
16    Fasteners    3001.9600

In [27]:
query = """
SELECT
    Category,
    AVG(Sales) AS Average_Sales
FROM superstore_cleaned
GROUP BY Category;
"""

pd.read_sql(query, engine)

          Category  Average_Sales
0        Furniture     150.321454
1  Office Supplies      60.170687
2       Technology     158.852844